[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
x86_64 = "0.14.10"
uart_16550 = "0.2.18"
spin = "0.9"
bootloader = "0.11.2"
lazy_static = { version = "1.4", features = ["spin_no_std"] }

[features]
default = []

[build-dependencies]
